(define (average x y) 
  (/ (+ x y) 2))
(define (square x) 
  (* x x))
  
(define (cube-root x)
  (define (sqrt-iter guess x)
    (define (improve guess x)
      (/ (+ (/ x (square guess)) (* 2 guess)) 3))
    (define (good-enough? guess x) 
      (< (abs (- (square guess) x)) 0.1))
    (if (good-enough? guess x)
      guess 
      (sqrt-iter (improve guess x) x)))
  (sqrt-iter 3.0 x))
